title: Antonie Ermstrang # your name (or website title) here
logo: "/images/IMG_20200203_114150.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  Futures and Options Trader 
  <br><br>
  <a href="http://linkedin.com/in/antonie-ermstrang-16761193">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
